# -*- coding: utf-8 -*-
"""evaluate_gemini_cap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KDDvNfMT2cAH5Z0osTzRb3o28ZR_ebo-
"""

import json
import csv
from embedding_utils import cosine_similarity
#errro needs t be handled
"""
Loads Gemini and COCO captions from JSON files

Computes cosine similarity for each image

Outputs a CSV with max similarity, average similarity, gemini caption

Output saved in data/coco_subset/similarity_scores.csv
"""

def evaluate_captions(gemini_path, reference_path, output_csv):
    with open(gemini_path, "r") as f:
        gemini_captions = json.load(f)

    with open(reference_path, "r") as f:
        reference_captions = json.load(f)

    results = []
    total_max = 0
    total_avg = 0
    count = 0

    for filename, gemini_caption in gemini_captions.items():
        references = reference_captions.get(filename, [])
        if not references:
            continue

        scores = [cosine_similarity(gemini_caption, ref) for ref in references]
        max_score = max(scores)
        avg_score = sum(scores) / len(scores)

        total_max += max_score
        total_avg += avg_score
        count += 1


        results.append({
            "image": filename,
            "similarity_min": round(min(scores), 4),
            "similarity_max": round(max_score, 4),
            "similarity_avg": round(avg_score, 4),
            "gemini_caption": gemini_caption
        })

    # Calculate dataset-wide averages
    avg_max_score = round(total_max / count, 4)
    avg_avg_score = round(total_avg / count, 4)
    with open(output_csv, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=results[0].keys())
        writer.writeheader()
        writer.writerows(results)
        # Add average row
        writer.writerow({
            "image": "AVERAGE",
            "similarity_max": avg_max_score,
            "similarity_avg": avg_avg_score,
            "gemini_caption": "N/A"
        })

    print(f"Saved evaluation results to {output_csv}")


if __name__ == "__main__":
    evaluate_captions(
        gemini_path="data/coco_subset/gemini_captions.json",
        reference_path="data/coco_subset/references.json",
        output_csv="data/coco_subset/similarity_scores.csv"
    )